/*
 * MTIMER0_config.h
 *
 *  Created on: Jun 11, 2023
 *      Author: Elkhashab
 */

#ifndef MTIMER0_MTIMER0_CONFIG_H_
#define MTIMER0_MTIMER0_CONFIG_H_

/*
 * Please Config Timer Clock
 *
 * MTIMER0_NO_CLK
 * MTIMER0_PRESCALER_1
 * MTIMER0_PRESCALER_8
 * MTIMER0_PRESCALER_64
 * MTIMER0_PRESCALER_256
 * MTIMER0_PRESCALER_1024
 * MTIMER0_EXTCLK_FALL_EDGE
 * MTIMER0_EXTCLK_RISE_EDGE
 *
 */

#define MTIMER0_CLK MTIMER0_PRESCALER_256

/*
 * Please Config Timer0 Mode:
 *  MTIMER0_MODE_NORMAL
 *	MTIMER0_MODE_CTC
 *	MTIMER0_MODE_FAST_PWM
 *	MTIMER0_MODE_PHASE_CORRECT_PWM
 */

#define MTIMER0_MODE MTIMER0_MODE_PHASE_CORRECT_PWM

/*
 * Please Config Timer0 OC0 Pin Wave Generation:
 * MTIMER_OC0_DISCONNECTED
 * MTIMER_OC0_TOGGLER
 * MTIMER_OC0_CLEAR
 * MTIMER_OC0_SET
 *
 * For PWM:
 * MTIMER0_OC0_NONINVERTED
 * MTIMER0_OC0_INVERTED
 */

#define MTIMER0_OC0_MODE MTIMER0_OC0_NONINVERTED

#define FCPU 16UL

#endif /* MTIMER0_MTIMER0_CONFIG_H_ */
