/*
 * HTEMPREATURE_config.h
 *
 *  Created on: Jun 26, 2023
 *      Author: Elkhashab
 */

#ifndef HTEMPERATURE_HTEMPREATURE_CONFIG_H_
#define HTEMPERATURE_HTEMPREATURE_CONFIG_H_

#define LM35_CHANNEL	ADC_CHANNEL_0

#endif /* HTEMPERATURE_HTEMPREATURE_CONFIG_H_ */
